package message;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Package)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>optional string task_id = 1;</code>
     * @return Whether the taskId field is set.
     */
    boolean hasTaskId();
    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>optional string task_id = 1;</code>
     * @return The taskId.
     */
    java.lang.String getTaskId();
    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>optional string task_id = 1;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <pre>
     * 来源标识
     * </pre>
     *
     * <code>repeated string source = 2;</code>
     * @return A list containing the source.
     */
    java.util.List<java.lang.String>
        getSourceList();
    /**
     * <pre>
     * 来源标识
     * </pre>
     *
     * <code>repeated string source = 2;</code>
     * @return The count of source.
     */
    int getSourceCount();
    /**
     * <pre>
     * 来源标识
     * </pre>
     *
     * <code>repeated string source = 2;</code>
     * @param index The index of the element to return.
     * @return The source at the given index.
     */
    java.lang.String getSource(int index);
    /**
     * <pre>
     * 来源标识
     * </pre>
     *
     * <code>repeated string source = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the source at the given index.
     */
    com.google.protobuf.ByteString
        getSourceBytes(int index);

    /**
     * <code>required .Package.ATTRIBUTES attributes = 3;</code>
     * @return Whether the attributes field is set.
     */
    boolean hasAttributes();
    /**
     * <code>required .Package.ATTRIBUTES attributes = 3;</code>
     * @return The attributes.
     */
    Message.Package.ATTRIBUTES getAttributes();

    /**
     * <pre>
     * 数据base64加密
     * </pre>
     *
     * <code>optional string issue = 4;</code>
     * @return Whether the issue field is set.
     */
    boolean hasIssue();
    /**
     * <pre>
     * 数据base64加密
     * </pre>
     *
     * <code>optional string issue = 4;</code>
     * @return The issue.
     */
    java.lang.String getIssue();
    /**
     * <pre>
     * 数据base64加密
     * </pre>
     *
     * <code>optional string issue = 4;</code>
     * @return The bytes for issue.
     */
    com.google.protobuf.ByteString
        getIssueBytes();

    /**
     * <pre>
     * 回调地址
     * </pre>
     *
     * <code>optional string callback = 5;</code>
     * @return Whether the callback field is set.
     */
    boolean hasCallback();
    /**
     * <pre>
     * 回调地址
     * </pre>
     *
     * <code>optional string callback = 5;</code>
     * @return The callback.
     */
    java.lang.String getCallback();
    /**
     * <pre>
     * 回调地址
     * </pre>
     *
     * <code>optional string callback = 5;</code>
     * @return The bytes for callback.
     */
    com.google.protobuf.ByteString
        getCallbackBytes();

    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>optional int64 timestamp = 6;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>optional int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code Package}
   */
  public static final class Package extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Package)
      PackageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Package.newBuilder() to construct.
    private Package(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Package() {
      taskId_ = "";
      source_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      attributes_ = 0;
      issue_ = "";
      callback_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Package();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Package(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              taskId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                source_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              source_.add(bs);
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              Message.Package.ATTRIBUTES value = Message.Package.ATTRIBUTES.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                attributes_ = rawValue;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              issue_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              callback_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          source_ = source_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_Package_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_Package_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.Package.class, Message.Package.Builder.class);
    }

    /**
     * <pre>
     * 数据包属性
     * </pre>
     *
     * Protobuf enum {@code Package.ATTRIBUTES}
     */
    public enum ATTRIBUTES
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 心跳
       * </pre>
       *
       * <code>HEARTBEAT = 0;</code>
       */
      HEARTBEAT(0),
      /**
       * <pre>
       * 执行任务
       * </pre>
       *
       * <code>ISSUE_TASK = 1;</code>
       */
      ISSUE_TASK(1),
      /**
       * <pre>
       * 取消任务
       * </pre>
       *
       * <code>CANCEL_TASK = 2;</code>
       */
      CANCEL_TASK(2),
      /**
       * <pre>
       * 添加任务
       * </pre>
       *
       * <code>ADD_TASK = 3;</code>
       */
      ADD_TASK(3),
      ;

      /**
       * <pre>
       * 心跳
       * </pre>
       *
       * <code>HEARTBEAT = 0;</code>
       */
      public static final int HEARTBEAT_VALUE = 0;
      /**
       * <pre>
       * 执行任务
       * </pre>
       *
       * <code>ISSUE_TASK = 1;</code>
       */
      public static final int ISSUE_TASK_VALUE = 1;
      /**
       * <pre>
       * 取消任务
       * </pre>
       *
       * <code>CANCEL_TASK = 2;</code>
       */
      public static final int CANCEL_TASK_VALUE = 2;
      /**
       * <pre>
       * 添加任务
       * </pre>
       *
       * <code>ADD_TASK = 3;</code>
       */
      public static final int ADD_TASK_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ATTRIBUTES valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ATTRIBUTES forNumber(int value) {
        switch (value) {
          case 0: return HEARTBEAT;
          case 1: return ISSUE_TASK;
          case 2: return CANCEL_TASK;
          case 3: return ADD_TASK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ATTRIBUTES>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ATTRIBUTES> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ATTRIBUTES>() {
              public ATTRIBUTES findValueByNumber(int number) {
                return ATTRIBUTES.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.Package.getDescriptor().getEnumTypes().get(0);
      }

      private static final ATTRIBUTES[] VALUES = values();

      public static ATTRIBUTES valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ATTRIBUTES(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Package.ATTRIBUTES)
    }

    private int bitField0_;
    public static final int TASK_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskId_;
    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>optional string task_id = 1;</code>
     * @return Whether the taskId field is set.
     */
    @java.lang.Override
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>optional string task_id = 1;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 任务ID
     * </pre>
     *
     * <code>optional string task_id = 1;</code>
     * @return The bytes for taskId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList source_;
    /**
     * <pre>
     * 来源标识
     * </pre>
     *
     * <code>repeated string source = 2;</code>
     * @return A list containing the source.
     */
    public com.google.protobuf.ProtocolStringList
        getSourceList() {
      return source_;
    }
    /**
     * <pre>
     * 来源标识
     * </pre>
     *
     * <code>repeated string source = 2;</code>
     * @return The count of source.
     */
    public int getSourceCount() {
      return source_.size();
    }
    /**
     * <pre>
     * 来源标识
     * </pre>
     *
     * <code>repeated string source = 2;</code>
     * @param index The index of the element to return.
     * @return The source at the given index.
     */
    public java.lang.String getSource(int index) {
      return source_.get(index);
    }
    /**
     * <pre>
     * 来源标识
     * </pre>
     *
     * <code>repeated string source = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the source at the given index.
     */
    public com.google.protobuf.ByteString
        getSourceBytes(int index) {
      return source_.getByteString(index);
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 3;
    private int attributes_;
    /**
     * <code>required .Package.ATTRIBUTES attributes = 3;</code>
     * @return Whether the attributes field is set.
     */
    @java.lang.Override public boolean hasAttributes() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .Package.ATTRIBUTES attributes = 3;</code>
     * @return The attributes.
     */
    @java.lang.Override public Message.Package.ATTRIBUTES getAttributes() {
      @SuppressWarnings("deprecation")
      Message.Package.ATTRIBUTES result = Message.Package.ATTRIBUTES.valueOf(attributes_);
      return result == null ? Message.Package.ATTRIBUTES.HEARTBEAT : result;
    }

    public static final int ISSUE_FIELD_NUMBER = 4;
    private volatile java.lang.Object issue_;
    /**
     * <pre>
     * 数据base64加密
     * </pre>
     *
     * <code>optional string issue = 4;</code>
     * @return Whether the issue field is set.
     */
    @java.lang.Override
    public boolean hasIssue() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 数据base64加密
     * </pre>
     *
     * <code>optional string issue = 4;</code>
     * @return The issue.
     */
    @java.lang.Override
    public java.lang.String getIssue() {
      java.lang.Object ref = issue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          issue_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 数据base64加密
     * </pre>
     *
     * <code>optional string issue = 4;</code>
     * @return The bytes for issue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIssueBytes() {
      java.lang.Object ref = issue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        issue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CALLBACK_FIELD_NUMBER = 5;
    private volatile java.lang.Object callback_;
    /**
     * <pre>
     * 回调地址
     * </pre>
     *
     * <code>optional string callback = 5;</code>
     * @return Whether the callback field is set.
     */
    @java.lang.Override
    public boolean hasCallback() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 回调地址
     * </pre>
     *
     * <code>optional string callback = 5;</code>
     * @return The callback.
     */
    @java.lang.Override
    public java.lang.String getCallback() {
      java.lang.Object ref = callback_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          callback_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 回调地址
     * </pre>
     *
     * <code>optional string callback = 5;</code>
     * @return The bytes for callback.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCallbackBytes() {
      java.lang.Object ref = callback_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callback_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>optional int64 timestamp = 6;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>optional int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAttributes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
      }
      for (int i = 0; i < source_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, source_.getRaw(i));
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(3, attributes_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, issue_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, callback_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt64(6, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < source_.size(); i++) {
          dataSize += computeStringSizeNoTag(source_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSourceList().size();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, attributes_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, issue_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, callback_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message.Package)) {
        return super.equals(obj);
      }
      Message.Package other = (Message.Package) obj;

      if (hasTaskId() != other.hasTaskId()) return false;
      if (hasTaskId()) {
        if (!getTaskId()
            .equals(other.getTaskId())) return false;
      }
      if (!getSourceList()
          .equals(other.getSourceList())) return false;
      if (hasAttributes() != other.hasAttributes()) return false;
      if (hasAttributes()) {
        if (attributes_ != other.attributes_) return false;
      }
      if (hasIssue() != other.hasIssue()) return false;
      if (hasIssue()) {
        if (!getIssue()
            .equals(other.getIssue())) return false;
      }
      if (hasCallback() != other.hasCallback()) return false;
      if (hasCallback()) {
        if (!getCallback()
            .equals(other.getCallback())) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTaskId()) {
        hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
        hash = (53 * hash) + getTaskId().hashCode();
      }
      if (getSourceCount() > 0) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSourceList().hashCode();
      }
      if (hasAttributes()) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + attributes_;
      }
      if (hasIssue()) {
        hash = (37 * hash) + ISSUE_FIELD_NUMBER;
        hash = (53 * hash) + getIssue().hashCode();
      }
      if (hasCallback()) {
        hash = (37 * hash) + CALLBACK_FIELD_NUMBER;
        hash = (53 * hash) + getCallback().hashCode();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message.Package parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.Package parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.Package parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.Package parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.Package parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message.Package parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message.Package parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.Package parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.Package parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message.Package parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message.Package parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message.Package parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message.Package prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Package}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Package)
        Message.PackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_Package_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_Package_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.Package.class, Message.Package.Builder.class);
      }

      // Construct using Message.Package.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        taskId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        attributes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        issue_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        callback_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_Package_descriptor;
      }

      @java.lang.Override
      public Message.Package getDefaultInstanceForType() {
        return Message.Package.getDefaultInstance();
      }

      @java.lang.Override
      public Message.Package build() {
        Message.Package result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Message.Package buildPartial() {
        Message.Package result = new Message.Package(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskId_ = taskId_;
        if (((bitField0_ & 0x00000002) != 0)) {
          source_ = source_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.attributes_ = attributes_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.issue_ = issue_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.callback_ = callback_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message.Package) {
          return mergeFrom((Message.Package)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message.Package other) {
        if (other == Message.Package.getDefaultInstance()) return this;
        if (other.hasTaskId()) {
          bitField0_ |= 0x00000001;
          taskId_ = other.taskId_;
          onChanged();
        }
        if (!other.source_.isEmpty()) {
          if (source_.isEmpty()) {
            source_ = other.source_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSourceIsMutable();
            source_.addAll(other.source_);
          }
          onChanged();
        }
        if (other.hasAttributes()) {
          setAttributes(other.getAttributes());
        }
        if (other.hasIssue()) {
          bitField0_ |= 0x00000008;
          issue_ = other.issue_;
          onChanged();
        }
        if (other.hasCallback()) {
          bitField0_ |= 0x00000010;
          callback_ = other.callback_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAttributes()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message.Package parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message.Package) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskId_ = "";
      /**
       * <pre>
       * 任务ID
       * </pre>
       *
       * <code>optional string task_id = 1;</code>
       * @return Whether the taskId field is set.
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 任务ID
       * </pre>
       *
       * <code>optional string task_id = 1;</code>
       * @return The taskId.
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 任务ID
       * </pre>
       *
       * <code>optional string task_id = 1;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 任务ID
       * </pre>
       *
       * <code>optional string task_id = 1;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务ID
       * </pre>
       *
       * <code>optional string task_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务ID
       * </pre>
       *
       * <code>optional string task_id = 1;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        taskId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList source_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSourceIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          source_ = new com.google.protobuf.LazyStringArrayList(source_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * 来源标识
       * </pre>
       *
       * <code>repeated string source = 2;</code>
       * @return A list containing the source.
       */
      public com.google.protobuf.ProtocolStringList
          getSourceList() {
        return source_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 来源标识
       * </pre>
       *
       * <code>repeated string source = 2;</code>
       * @return The count of source.
       */
      public int getSourceCount() {
        return source_.size();
      }
      /**
       * <pre>
       * 来源标识
       * </pre>
       *
       * <code>repeated string source = 2;</code>
       * @param index The index of the element to return.
       * @return The source at the given index.
       */
      public java.lang.String getSource(int index) {
        return source_.get(index);
      }
      /**
       * <pre>
       * 来源标识
       * </pre>
       *
       * <code>repeated string source = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the source at the given index.
       */
      public com.google.protobuf.ByteString
          getSourceBytes(int index) {
        return source_.getByteString(index);
      }
      /**
       * <pre>
       * 来源标识
       * </pre>
       *
       * <code>repeated string source = 2;</code>
       * @param index The index to set the value at.
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSourceIsMutable();
        source_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来源标识
       * </pre>
       *
       * <code>repeated string source = 2;</code>
       * @param value The source to add.
       * @return This builder for chaining.
       */
      public Builder addSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSourceIsMutable();
        source_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来源标识
       * </pre>
       *
       * <code>repeated string source = 2;</code>
       * @param values The source to add.
       * @return This builder for chaining.
       */
      public Builder addAllSource(
          java.lang.Iterable<java.lang.String> values) {
        ensureSourceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, source_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来源标识
       * </pre>
       *
       * <code>repeated string source = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        source_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来源标识
       * </pre>
       *
       * <code>repeated string source = 2;</code>
       * @param value The bytes of the source to add.
       * @return This builder for chaining.
       */
      public Builder addSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSourceIsMutable();
        source_.add(value);
        onChanged();
        return this;
      }

      private int attributes_ = 0;
      /**
       * <code>required .Package.ATTRIBUTES attributes = 3;</code>
       * @return Whether the attributes field is set.
       */
      @java.lang.Override public boolean hasAttributes() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required .Package.ATTRIBUTES attributes = 3;</code>
       * @return The attributes.
       */
      @java.lang.Override
      public Message.Package.ATTRIBUTES getAttributes() {
        @SuppressWarnings("deprecation")
        Message.Package.ATTRIBUTES result = Message.Package.ATTRIBUTES.valueOf(attributes_);
        return result == null ? Message.Package.ATTRIBUTES.HEARTBEAT : result;
      }
      /**
       * <code>required .Package.ATTRIBUTES attributes = 3;</code>
       * @param value The attributes to set.
       * @return This builder for chaining.
       */
      public Builder setAttributes(Message.Package.ATTRIBUTES value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        attributes_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Package.ATTRIBUTES attributes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttributes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        attributes_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object issue_ = "";
      /**
       * <pre>
       * 数据base64加密
       * </pre>
       *
       * <code>optional string issue = 4;</code>
       * @return Whether the issue field is set.
       */
      public boolean hasIssue() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 数据base64加密
       * </pre>
       *
       * <code>optional string issue = 4;</code>
       * @return The issue.
       */
      public java.lang.String getIssue() {
        java.lang.Object ref = issue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            issue_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 数据base64加密
       * </pre>
       *
       * <code>optional string issue = 4;</code>
       * @return The bytes for issue.
       */
      public com.google.protobuf.ByteString
          getIssueBytes() {
        java.lang.Object ref = issue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          issue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 数据base64加密
       * </pre>
       *
       * <code>optional string issue = 4;</code>
       * @param value The issue to set.
       * @return This builder for chaining.
       */
      public Builder setIssue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        issue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据base64加密
       * </pre>
       *
       * <code>optional string issue = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIssue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        issue_ = getDefaultInstance().getIssue();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据base64加密
       * </pre>
       *
       * <code>optional string issue = 4;</code>
       * @param value The bytes for issue to set.
       * @return This builder for chaining.
       */
      public Builder setIssueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        issue_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object callback_ = "";
      /**
       * <pre>
       * 回调地址
       * </pre>
       *
       * <code>optional string callback = 5;</code>
       * @return Whether the callback field is set.
       */
      public boolean hasCallback() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 回调地址
       * </pre>
       *
       * <code>optional string callback = 5;</code>
       * @return The callback.
       */
      public java.lang.String getCallback() {
        java.lang.Object ref = callback_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            callback_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 回调地址
       * </pre>
       *
       * <code>optional string callback = 5;</code>
       * @return The bytes for callback.
       */
      public com.google.protobuf.ByteString
          getCallbackBytes() {
        java.lang.Object ref = callback_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          callback_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 回调地址
       * </pre>
       *
       * <code>optional string callback = 5;</code>
       * @param value The callback to set.
       * @return This builder for chaining.
       */
      public Builder setCallback(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        callback_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 回调地址
       * </pre>
       *
       * <code>optional string callback = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCallback() {
        bitField0_ = (bitField0_ & ~0x00000010);
        callback_ = getDefaultInstance().getCallback();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 回调地址
       * </pre>
       *
       * <code>optional string callback = 5;</code>
       * @param value The bytes for callback to set.
       * @return This builder for chaining.
       */
      public Builder setCallbackBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        callback_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>optional int64 timestamp = 6;</code>
       * @return Whether the timestamp field is set.
       */
      @java.lang.Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>optional int64 timestamp = 6;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>optional int64 timestamp = 6;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间戳
       * </pre>
       *
       * <code>optional int64 timestamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Package)
    }

    // @@protoc_insertion_point(class_scope:Package)
    private static final Message.Package DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message.Package();
    }

    public static Message.Package getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Package>
        PARSER = new com.google.protobuf.AbstractParser<Package>() {
      @java.lang.Override
      public Package parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Package(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Package> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Package> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Message.Package getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Package_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Package_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"\323\001\n\007Package\022\017\n\007task_id\030\001" +
      " \001(\t\022\016\n\006source\030\002 \003(\t\022\'\n\nattributes\030\003 \002(\016" +
      "2\023.Package.ATTRIBUTES\022\r\n\005issue\030\004 \001(\t\022\020\n\010" +
      "callback\030\005 \001(\t\022\021\n\ttimestamp\030\006 \001(\003\"J\n\nATT" +
      "RIBUTES\022\r\n\tHEARTBEAT\020\000\022\016\n\nISSUE_TASK\020\001\022\017" +
      "\n\013CANCEL_TASK\020\002\022\014\n\010ADD_TASK\020\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Package_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Package_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Package_descriptor,
        new java.lang.String[] { "TaskId", "Source", "Attributes", "Issue", "Callback", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
